# Fusion MPT drivers; recognized debug defines...

# enable verbose logging
# CONFIG_FUSION_LOGGING needs to be enabled in Kconfig
#ccflags-y := -DMPT_DEBUG_VERBOSE


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-} LSI_LOGIC

obj-m	+= mptbase.o mptscsih.o mptspi.o
obj-m		+= mptbase.o mptscsih.o mptfc.o
obj-m	+= mptbase.o mptscsih.o mptsas.o
obj-m	+= mptctl.o
obj-m	+= mptlan.o
