# SPDX-License-Identifier: GPL-2.0-only

# netvsc_trace.h's TRACE_INCLUDE_PATH needs to be modified.

obj-$(CONFIG_HYPERV_NET) += hv_netvsc.o

hv_netvsc-y := netvsc_drv.o netvsc.o rndis_filter.o netvsc_trace.o netvsc_bpf.o
