#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Get official modules

on:   
  workflow_dispatch:

jobs:
  official:
    runs-on: ubuntu-latest
    env:
      TOOL_PATH: extractor
      OFFICIAL_PATH: official
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Init Env
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Get extractor
        run: |
          echo "Getting syno extractor"
          TOOL_PATH="${{ env.TOOL_PATH }}"
          CACHE_DIR="/tmp/pat"

          rm -rf "${TOOL_PATH}"
          mkdir -p "${TOOL_PATH}"
          rm -rf "${CACHE_DIR}"
          mkdir -p "${CACHE_DIR}"

          OLDPAT_URL="https://global.download.synology.com/download/DSM/release/7.0.1/42218/DSM_DS3622xs%2B_42218.pat"
          OLDPAT_FILE="DSM_DS3622xs+_42218.pat"
          STATUS=`curl -# -w "%{http_code}" -L "${OLDPAT_URL}" -o "${CACHE_DIR}/${OLDPAT_FILE}"`
          if [ $? -ne 0 -o ${STATUS} -ne 200 ]; then
            echo "[E] DSM_DS3622xs%2B_42218.pat download error!"
            rm -rf ${CACHE_DIR}
            exit 1
          fi

          mkdir -p "${CACHE_DIR}/ramdisk"
          tar -C "${CACHE_DIR}/ramdisk/" -xf "${CACHE_DIR}/${OLDPAT_FILE}" rd.gz 2>&1
          if [ $? -ne 0 ]; then
            echo "[E] extractor rd.gz error!"
            rm -rf ${CACHE_DIR}
            exit 1
          fi
          (cd "${CACHE_DIR}/ramdisk"; xz -dc < rd.gz | cpio -idm) >/dev/null 2>&1 || true

          # Copy only necessary files
          for f in libcurl.so.4 libmbedcrypto.so.5 libmbedtls.so.13 libmbedx509.so.1 libmsgpackc.so.2 libsodium.so libsynocodesign-ng-virtual-junior-wins.so.7; do
            cp "${CACHE_DIR}/ramdisk/usr/lib/${f}" "${TOOL_PATH}"
          done
          cp "${CACHE_DIR}/ramdisk/usr/syno/bin/scemd" "${TOOL_PATH}/syno_extract_system_patch"
          rm -rf ${CACHE_DIR}

      - name: Get official modules
        run: |
          function getOfficialModules(){
            filename=${1}
            filename=${filename##*\/}
            filename=${filename%%\?*}
            filepath=${filename%%\.*}

            echo "Download ${1}"
            curl -#kO "${1}"

            header="$(od -bcN2 ${filename} | head -1 | awk '{print $3}')"
            case ${header} in
              105)
                echo "Uncompressed tar"
                isencrypted="no"
                ;;
              213)
                echo "Compressed tar"
                isencrypted="no"
                ;;
              255)
                echo "Encrypted"
                isencrypted="yes"
                ;;
              *)
                echo "error"
                return 1
                ;;
            esac
            
            echo "extract ${filename}"
            mkdir -p "${filepath}"
            if [ "${isencrypted}" = "yes" ]; then
              TOOL_PATH="${{ env.TOOL_PATH }}"
              sudo chmod -R +x "${TOOL_PATH}"
              sudo LD_LIBRARY_PATH="${TOOL_PATH}" "${TOOL_PATH}/syno_extract_system_patch" "${filename}" "${filepath}"
            else
              tar -xf "${filename}" -C "${filepath}" >/dev/null 2>&1
            fi

            echo "extract ${filepath}/rd.gz"
            rdpath=`realpath ${filepath}/rd.gz`
            rdpath=${rdpath%%\.*}
            mkdir -p "${rdpath}"
            (cd "${rdpath}"; xz -dc < "${rdpath}.gz" | cpio -idm) >/dev/null 2>&1 || true
            
            plat="`grep unique "${filepath}/VERSION" | sed -r 's/.*_(.*)_.*/\1/'`"
            kver="`file "${filepath}/zImage" | awk '{printf $9}' | sed 's/+//g'`"
            officialpath="${{ env.OFFICIAL_PATH }}/${plat}-${kver}"

            echo "copy ${plat}-${kver} modules"
            [ ! -d "${{ env.OFFICIAL_PATH }}" ] && mkdir -p "${{ env.OFFICIAL_PATH }}"
            rm -rf "${officialpath}"
            cp -a ${rdpath}/usr/lib/modules "${officialpath}"

            sudo rm -rf "${filename}" "${filepath}"
          }

          #- version: 6.2.4 
          #  platform: apollolake
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/6.2.4/25556/DSM_DS918%2B_25556.pat'
          #- version: 6.2.4 
          #  platform: braswell
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/6.2.4/25556/DSM_DS916%2B_25556.pat'
          #- version: 6.2.4 
          #  platform: broadwell
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/6.2.4/25556/DSM_DS3617xs_25556.pat'
          #- version: 6.2.4 
          #  platform: broadwellnk
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/6.2.4/25556/DSM_DS1621xs%2B_25556.pat'  # DS3622xs%2B no have version 6.2.4
          #- version: 6.2.4 
          #  platform: bromolow
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/6.2.4/25556/DSM_DS3615xs_25556.pat'
          #- version: 6.2.4 
          #  platform: denverton
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/6.2.4/25556/DSM_DVA3221_25556.pat'
          #- version: 6.2.4 
          #  platform: geminilake
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/6.2.4/25556/DSM_DS920%2B_25556.pat'  # DVA1622 have i915.ko, but only supports 2nd to 9th gen, no have version 6.2.4.
          #- version: 6.2.4 
          #  platform: purley
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/6.2.4/25556/DSM_FS6400_25556.pat'
          #- version: 6.2.4 
          #  platform: v1000
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/6.2.4/25556/DSM_DS1621%2B_25556.pat'
          #- version: 6.2.4 
          #  platform: kvmx64
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/6.2.4/25556/DSM_VirtualDSM_25556.pat'

          #- version: 7.1 
          #  platform: apollolake
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.0.1/42218/DSM_DS918%2B_42218.pat'
          #- version: 7.1
          #  platform: braswell
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.0.1/42218/DSM_DS916%2B_42218.pat'
          #- version: 7.1
          #  platform: broadwell
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.0.1/42218/DSM_DS3617xs_42218.pat'
          #- version: 7.1 
          #  platform: broadwellnk
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.0.1/42218/DSM_DS3622xs%2B_42218.pat'
          #- version: 7.1 
          #  platform: bromolow
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.0.1/42218/DSM_DS3615xs_42218.pat'
          #- version: 7.1
          #  platform: denverton
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.0.1/42218/DSM_DVA3221_42218.pat'
          ##- version: 7.1
          ##  platform: epyc7002
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.1.1/42962/DSM_SA6400_42962.pat'
          #- version: 7.1 
          #  platform: geminilake
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.1/42661-1/DSM_DVA1622_42661.pat'  # DVA1622 have i915.ko, but only supports 2nd to 9th gen.
          #- version: 7.1 
          #  platform: purley
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.0.1/42218/DSM_FS6400_42218.pat'
          #- version: 7.1
          #  platform: r1000
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.1.1/42962/DSM_DS923%2B_42962.pat'  # DS923%2B no have version 7.0.1
          #- version: 7.1
          #  platform: v1000
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.0.1/42218/DSM_DS1621%2B_42218.pat'
          #- version: 7.1
          #  platform: kvmx64
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat'

          #- version: 7.2 
          #  platform: apollolake
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_DS918%2B_64570.pat'
          #- version: 7.2
          #  platform: braswell
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_DS916%2B_64570.pat'
          #- version: 7.2
          #  platform: broadwell
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_DS3617xs_64570.pat'
          #- version: 7.2 
          #  platform: broadwellnk
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_DS3622xs%2B_64570.pat'
          ##- version: 7.2 
          ##  platform: bromolow
          #getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_DS3615xs_64570.pat'
          #- version: 7.2
          #  platform: denverton
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_DVA3221_64570.pat'
          #- version: 7.2
          #  platform: epyc7002
          #getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_SA6400_64570.pat'
          #- version: 7.2 
          #  platform: geminilake
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_DVA1622_64570.pat'  # DVA1622 have i915.ko, but only supports 2nd to 9th gen.
          #- version: 7.2 
          #  platform: purley
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_FS6400_64570.pat'
          #- version: 7.2
          #  platform: r1000
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_DS923%2B_64570.pat'
          #- version: 7.2
          #  platform: v1000
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_DS1621%2B_64570.pat'
          #- version: 7.2
          #  platform: kvmx64
          getOfficialModules 'https://global.synologydownload.com/download/DSM/release/7.2/64570/DSM_VirtualDSM_64570.pat'

      - name: Check and Push
        run: |
          git pull
          status=$(git status -s | grep -E '${{ env.OFFICIAL_PATH }}' | awk '{printf " %s", $2}')
          if [ -n "${status}" ]; then
            git add ${status}
            git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
            git push -f
          fi